
$ node liri.js
this is loaded
[ { created_at: 'Tue Apr 03 17:52:09 +0000 2018',
    id: 981227872768667600,
    id_str: '981227872768667648',
    text: 'Houston weather is perfect...... for those 2 days out of the year',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 981226961816248300,
       id_str: '981226961816248321',
       name: 'ozair khan',
       screen_name: 'ozzysworld3',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 0,
       friends_count: 0,
       listed_count: 0,
       created_at: 'Tue Apr 03 17:48:32 +0000 2018',
       favourites_count: 1,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 4,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: true,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Tue Apr 03 17:51:23 +0000 2018',
    id: 981227678572347400,
    id_str: '981227678572347393',
    text: 'The Rockets are taking it all this year! no question about it 🤠',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 981226961816248300,
       id_str: '981226961816248321',
       name: 'ozair khan',
       screen_name: 'ozzysworld3',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 0,
       friends_count: 0,
       listed_count: 0,
       created_at: 'Tue Apr 03 17:48:32 +0000 2018',
       favourites_count: 1,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 4,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: true,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Tue Apr 03 17:50:58 +0000 2018',
    id: 981227572527759400,
    id_str: '981227572527759360',
    text: 'Nice day at Hermann Park!',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 981226961816248300,
       id_str: '981226961816248321',
       name: 'ozair khan',
       screen_name: 'ozzysworld3',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 0,
       friends_count: 0,
       listed_count: 0,
       created_at: 'Tue Apr 03 17:48:32 +0000 2018',
       favourites_count: 1,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 4,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: true,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Tue Apr 03 17:50:38 +0000 2018',
    id: 981227488595664900,
    id_str: '981227488595664896',
    text: 'just doing some node challenges right now. #serverSide',
    truncated: false,
    entities: { hashtags: [Array], symbols: [], user_mentions: [], urls: [] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 981226961816248300,
       id_str: '981226961816248321',
       name: 'ozair khan',
       screen_name: 'ozzysworld3',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 0,
       friends_count: 0,
       listed_count: 0,
       created_at: 'Tue Apr 03 17:48:32 +0000 2018',
       favourites_count: 1,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 4,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: true,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 1,
    favorited: true,
    retweeted: false,
    lang: 'en' } ]